tunnel: 5c750be0-948e-4203-a255-38936cc16c01
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: shellton.app
    service: http://web:3000
  - hostname: www.shellton.app
    service: http://web:3000
  - service: http_status:404
